/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as BlogRouteImport } from './routes/blog'
import { Route as ConsultationRouteImport } from './routes/consultation'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as DigitalProductsRouteImport } from './routes/digital-products'
import { Route as FarmVisitRouteImport } from './routes/farm-visit'
import { Route as PoultryProductsRouteImport } from './routes/poultry-products'
import { Route as ProductsServicesRouteImport } from './routes/products-services'
import { Route as TestimonialsRouteImport } from './routes/testimonials'
import { Route as TrainingRouteImport } from './routes/training'
import { Route as ApiPublicPushDispatchRouteImport } from './routes/api/public/push-dispatch'
import { Route as OauthGoogleCalendarReturnRouteImport } from './routes/oauth.google-calendar.return'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogRoute = BlogRouteImport.update({
  id: '/blog',
  path: '/blog',
  getParentRoute: () => rootRouteImport,
} as any)
const ConsultationRoute = ConsultationRouteImport.update({
  id: '/consultation',
  path: '/consultation',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const DigitalProductsRoute = DigitalProductsRouteImport.update({
  id: '/digital-products',
  path: '/digital-products',
  getParentRoute: () => rootRouteImport,
} as any)
const FarmVisitRoute = FarmVisitRouteImport.update({
  id: '/farm-visit',
  path: '/farm-visit',
  getParentRoute: () => rootRouteImport,
} as any)
const PoultryProductsRoute = PoultryProductsRouteImport.update({
  id: '/poultry-products',
  path: '/poultry-products',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductsServicesRoute = ProductsServicesRouteImport.update({
  id: '/products-services',
  path: '/products-services',
  getParentRoute: () => rootRouteImport,
} as any)
const TestimonialsRoute = TestimonialsRouteImport.update({
  id: '/testimonials',
  path: '/testimonials',
  getParentRoute: () => rootRouteImport,
} as any)
const TrainingRoute = TrainingRouteImport.update({
  id: '/training',
  path: '/training',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicPushDispatchRoute = ApiPublicPushDispatchRouteImport.update({
  id: '/api/public/push-dispatch',
  path: '/api/public/push-dispatch',
  getParentRoute: () => rootRouteImport,
} as any)
const OauthGoogleCalendarReturnRoute =
  OauthGoogleCalendarReturnRouteImport.update({
    id: '/oauth/google-calendar/return',
    path: '/oauth/google-calendar/return',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRoute
  '/blog': typeof BlogRoute
  '/consultation': typeof ConsultationRoute
  '/contact': typeof ContactRoute
  '/digital-products': typeof DigitalProductsRoute
  '/farm-visit': typeof FarmVisitRoute
  '/poultry-products': typeof PoultryProductsRoute
  '/products-services': typeof ProductsServicesRoute
  '/testimonials': typeof TestimonialsRoute
  '/training': typeof TrainingRoute
  '/api/public/push-dispatch': typeof ApiPublicPushDispatchRoute
  '/oauth/google-calendar/return': typeof OauthGoogleCalendarReturnRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRoute
  '/blog': typeof BlogRoute
  '/consultation': typeof ConsultationRoute
  '/contact': typeof ContactRoute
  '/digital-products': typeof DigitalProductsRoute
  '/farm-visit': typeof FarmVisitRoute
  '/poultry-products': typeof PoultryProductsRoute
  '/products-services': typeof ProductsServicesRoute
  '/testimonials': typeof TestimonialsRoute
  '/training': typeof TrainingRoute
  '/api/public/push-dispatch': typeof ApiPublicPushDispatchRoute
  '/oauth/google-calendar/return': typeof OauthGoogleCalendarReturnRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRoute
  '/blog': typeof BlogRoute
  '/consultation': typeof ConsultationRoute
  '/contact': typeof ContactRoute
  '/digital-products': typeof DigitalProductsRoute
  '/farm-visit': typeof FarmVisitRoute
  '/poultry-products': typeof PoultryProductsRoute
  '/products-services': typeof ProductsServicesRoute
  '/testimonials': typeof TestimonialsRoute
  '/training': typeof TrainingRoute
  '/api/public/push-dispatch': typeof ApiPublicPushDispatchRoute
  '/oauth/google-calendar/return': typeof OauthGoogleCalendarReturnRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/admin'
    | '/blog'
    | '/consultation'
    | '/contact'
    | '/digital-products'
    | '/farm-visit'
    | '/poultry-products'
    | '/products-services'
    | '/testimonials'
    | '/training'
    | '/api/public/push-dispatch'
    | '/oauth/google-calendar/return'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/admin'
    | '/blog'
    | '/consultation'
    | '/contact'
    | '/digital-products'
    | '/farm-visit'
    | '/poultry-products'
    | '/products-services'
    | '/testimonials'
    | '/training'
    | '/api/public/push-dispatch'
    | '/oauth/google-calendar/return'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/admin'
    | '/blog'
    | '/consultation'
    | '/contact'
    | '/digital-products'
    | '/farm-visit'
    | '/poultry-products'
    | '/products-services'
    | '/testimonials'
    | '/training'
    | '/api/public/push-dispatch'
    | '/oauth/google-calendar/return'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AdminRoute: typeof AdminRoute
  BlogRoute: typeof BlogRoute
  ConsultationRoute: typeof ConsultationRoute
  ContactRoute: typeof ContactRoute
  DigitalProductsRoute: typeof DigitalProductsRoute
  FarmVisitRoute: typeof FarmVisitRoute
  PoultryProductsRoute: typeof PoultryProductsRoute
  ProductsServicesRoute: typeof ProductsServicesRoute
  TestimonialsRoute: typeof TestimonialsRoute
  TrainingRoute: typeof TrainingRoute
  ApiPublicPushDispatchRoute: typeof ApiPublicPushDispatchRoute
  OauthGoogleCalendarReturnRoute: typeof OauthGoogleCalendarReturnRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog': {
      id: '/blog'
      path: '/blog'
      fullPath: '/blog'
      preLoaderRoute: typeof BlogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/consultation': {
      id: '/consultation'
      path: '/consultation'
      fullPath: '/consultation'
      preLoaderRoute: typeof ConsultationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/digital-products': {
      id: '/digital-products'
      path: '/digital-products'
      fullPath: '/digital-products'
      preLoaderRoute: typeof DigitalProductsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/farm-visit': {
      id: '/farm-visit'
      path: '/farm-visit'
      fullPath: '/farm-visit'
      preLoaderRoute: typeof FarmVisitRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/poultry-products': {
      id: '/poultry-products'
      path: '/poultry-products'
      fullPath: '/poultry-products'
      preLoaderRoute: typeof PoultryProductsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products-services': {
      id: '/products-services'
      path: '/products-services'
      fullPath: '/products-services'
      preLoaderRoute: typeof ProductsServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/testimonials': {
      id: '/testimonials'
      path: '/testimonials'
      fullPath: '/testimonials'
      preLoaderRoute: typeof TestimonialsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/training': {
      id: '/training'
      path: '/training'
      fullPath: '/training'
      preLoaderRoute: typeof TrainingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/push-dispatch': {
      id: '/api/public/push-dispatch'
      path: '/api/public/push-dispatch'
      fullPath: '/api/public/push-dispatch'
      preLoaderRoute: typeof ApiPublicPushDispatchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/oauth/google-calendar/return': {
      id: '/oauth/google-calendar/return'
      path: '/oauth/google-calendar/return'
      fullPath: '/oauth/google-calendar/return'
      preLoaderRoute: typeof OauthGoogleCalendarReturnRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AdminRoute: AdminRoute,
  BlogRoute: BlogRoute,
  ConsultationRoute: ConsultationRoute,
  ContactRoute: ContactRoute,
  DigitalProductsRoute: DigitalProductsRoute,
  FarmVisitRoute: FarmVisitRoute,
  PoultryProductsRoute: PoultryProductsRoute,
  ProductsServicesRoute: ProductsServicesRoute,
  TestimonialsRoute: TestimonialsRoute,
  TrainingRoute: TrainingRoute,
  ApiPublicPushDispatchRoute: ApiPublicPushDispatchRoute,
  OauthGoogleCalendarReturnRoute: OauthGoogleCalendarReturnRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
